### ISSUE TITLE
Can't run on react-native 0.64 with enabled Hermes on iOS

### ISSUE THREAD

**Issue by irekrog** [cobrowseio/cobrowse-sdk-react-native#10]
In react-native 0.64 we can enable Hermes on iOS. But when Hermes is enabled then I have an error 
```
'exception' file not found
Could not build module 'React'
```
![cobrowebug](https://user-images.githubusercontent.com/11172548/112114587-8534b780-8bb8-11eb-9f32-9920a5097f54.jpg)

**Comment by irekrog** [comment]
@cobrowseio any update?

**Comment by headlessme** [comment]
@irekrog sorry not yet, we've had a lot going on! We're open to a PR if the fix is easy

**Comment by opeyemiagbeja** [comment]
any resolution on this? @headlessme
