### ISSUE TITLE
[tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Native module cannot be null.

### ISSUE THREAD

**Issue by msimons0** [cobrowseio/cobrowse-sdk-react-native#2]
![simulator screen shot - iphone x - 2018-10-19 at 13 09 10](https://user-images.githubusercontent.com/5008138/47241359-3c052b80-d3a0-11e8-8306-e9c456ee1a37.png)

react: 16.3.2
react native: 0.55.2
cobrowse-sdk-react-native: 1.1.5

The app crash as soon as you launch it

**Comment by headlessme** [comment]
Have you run the `react-native link` step? This will happen if the native side of the module isn't built into the app binary.

**Comment by headlessme** [comment]
Hope this solved your issue, please re-open if not
