### ISSUE TITLE
[compile error] Method does not override method from it's superclass

### ISSUE THREAD

**Issue by sumyfly** [cobrowseio/cobrowse-sdk-react-native#3]
When Android Studio compiles this library will stop with "Method does not override method from its superclass"  error on below source codes.
``` java    
    @Override
    public boolean shouldAllowKeyEvent(KeyEvent event, Session session) {
        return true;
    }

    @Override
    public boolean shouldAllowTouch(Touch event, Session session) {
        return true;
    }
```
It's just happened in recent days,  before it works.

**Comment by headlessme** [comment]
Should be fixed now, sorry for the inconvenience!

**Comment by sumyfly** [comment]
cool, thank you!
