### ISSUE TITLE
Problem with Carthage in version 2.3.0

### ISSUE THREAD

**Issue by Wertuoz** [cobrowseio/cobrowse-sdk-react-native#5]
Hello! Help me pease, i have a problem with version 2.3.0, trying to use with carthage, there are new dependencies of swift frameworks like SwiftCBOR and Starscream and I have an error trying to start app
http://snpy.in/I8ZGKu

Reason: Incompatible library version: CobrowseIO requires version 1.0.0 or later, but SwiftCBOR provides version 0.0.0

**Comment by headlessme** [comment]
Thanks for reporting, we're working on a fixed release for Carthage integration

**Comment by headlessme** [comment]
This should be resolved with the latest release of the underlying iOS SDK. Please reopen if you're still having issues.

**Comment by irekrog** [comment]
we have still the same problem 😢

**Comment by headlessme** [comment]
Can you confirm which version of the iOS SDK is being pulled in by your Carthage build, and also where the SwiftCBOR library is being pulled from?

**Comment by irekrog** [comment]
![Zrzut ekranu 2020-01-31 o 14 36 23](https://user-images.githubusercontent.com/11172548/73543647-b348bc80-4437-11ea-99bc-26f7b22f3be9.png)

Here is a data from pod and we use the most recent react native cobrowse sdk which is 2.3.0 and according to the github repo with this version (2.3.2) of cobrowseio the SwiftCBOR library is being pulled from cocoapods `s.dependency 'SwiftCBOR', '~> 0.4.3'`

**Comment by headlessme** [comment]
@irekrog This issue was specific to using Carthage rather than Pods, could you open a new issue with the exact error you're seeing?
