### ISSUE TITLE
Using Full Screen capabilities on iOS causes cocoapods to use an older version

### ISSUE THREAD

**Issue by lucaslt89** [cobrowseio/cobrowse-sdk-react-native#51]
In order to support full device capabilities, I added this to my podfile, according to the documentation: https://docs.cobrowse.io/sdk-features/full-device-capabilities/full-device-screen-sharing

```
# Cobrowse
pod 'CobrowseIO/Extension', '~>2'
```

That pod installs version 2.30.1 as of today, but the `cobrowse-sdk-react-native` package has version 2.29.5 as a dependency, so when we run `pod install`, this is the output:

```
Installing CobrowseIO 2.30.1
Installing CobrowseIO 2.29.5 (was 2.30.1)
```

As you can see, it installs **2.30.1** first (from `CobrowseIO/Extension`) and then replaces it by **2.29.5** from `cobrowse-sdk-react-native`

--

Could you update the dependency for this package to be the latest cobrowse SDK version?

**Comment by headlessme** [comment]
This has been released, please let us know if you run into any issues.
