### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by irekrog** [cobrowseio/cobrowse-sdk-react-native#6]
Using the most recent version of cobrowse-sdk-react-native results in missing files during iOS build process.

![73543647-b348bc80-4437-11ea-99bc-26f7b22f3be9](https://user-images.githubusercontent.com/11172548/74341714-7326f980-4da8-11ea-860e-f38c960808a8.png)

Hi, here is a data from pod and we use the most recent react native cobrowse sdk which is 2.3.0 and according to the github repo with this version (2.3.2) of cobrowseio the SwiftCBOR library is being pulled from cocoapods s.dependency 'SwiftCBOR', '~> 0.4.3'.

**Comment by headlessme** [comment]
Looks like there's a dependency missing from your Podfile. There should be a Starscream dependency too, e.g.

```
$ pod install 
Detected React Native module pod for cobrowse-sdk-react-native
Analyzing dependencies
Downloading dependencies
Installing CobrowseIO (2.3.2)
Installing Starscream (3.1.1)
Installing SwiftCBOR (0.4.3)
Installing cobrowse-sdk-react-native (2.3.0)
Generating Pods project
...
```

Can you confirm that that dependency is included somewhere? ?You can look at the Example folder in this repo which we have just updated to use the latest RN with Pods

**Comment by ramakula** [comment]
Yes. When we add it and run our project, this is the error we are seeing:
dyld: Library not loaded: @rpath/Starscream.framework/Starscream
  Referenced from: /Users/xxx/Library/Developer/CoreSimulator/Devices/77169DF9-06XX-442E-AC4F-BE1DA54D78F6/data/Containers/Bundle/Application/14666F04-3984-4EEA-8C49-AFFD27C395XX/xxx.app/Frameworks/CobrowseIO.framework/CobrowseIO
  Reason: image not found

**Comment by headlessme** [comment]
Could you post your full Podfile? We haven't managed to recreate the issue here yet. Which RN version and which version of the Cobrowse RN library are you using?

**Comment by ramakula** [comment]
We are using RN 61.5 ("react-native": "0.61.5",) and cobrowse version: "cobrowse-sdk-react-native": "^2.3.1",
Here is the snippet from our podfile:
target 'Acme' do
  quicken_shared_pods
  pod 'Intercom', :modular_headers => true
  pod 'AppsFlyerFramework', '4.10.4'
  pod 'cobrowse-sdk-react-native', :path => '../node_modules/cobrowse-sdk-react-native'

  target 'AcmeTests' do
      inherit! :search_paths
      # Pods for testing
  end

  target 'AcmeUITests' do
      inherit! :search_paths
      # Pods for testing
  end

After linking and everything, hen we run the app, this is error we are getting:
dyld: Library not loaded: @rpath/Starscream.framework/Starscream
Referenced from: /Users/xxx/Library/Developer/CoreSimulator/Devices/77169DF9-06XX-442E-AC4F-BE1DA54D78F6/data/Containers/Bundle/Application/14666F04-3984-4EEA-8C49-AFFD27C395XX/xxx.app/Frameworks/CobrowseIO.framework/CobrowseIO
Reason: image not found

I believe you are missing a dependency in your podspec file. I don't see  starscream dependency there?

**Comment by ramakula** [comment]
Or may be this will help: https://github.com/daltoniam/Starscream#add-copy-frameworks-phase
there should be a copy frameworks build phase in your cobrowse target?

**Comment by headlessme** [comment]
@ramakula we never ship our dependencies as part of our Framework as this would create a number of harder to solve issues, we rely on Pods to pull in the dependencies. Our Podspec file contains a dependency for Starscream (https://github.com/CocoaPods/Specs/blob/master/Specs/d/a/d/CobrowseIO/2.4.0/CobrowseIO.podspec.json) so if that's not being included it's likely an issue with your Pods setup. Starscream is written in Swift, so needs to be included as a Framework. Can you check that you have use_frameworks! in your Podfile?

**Comment by ramakula** [comment]
@headlessme ah that explains it but we do need to comment use_frameworks as other important dependencies that require this to be commented. I tried uncommenting it and most of our other (critical) dependencies fail. What are the other option we have in such case?

**Comment by headlessme** [comment]
Another option might be to use Carthage along side Pods, just for the Cobrowse dependencies. Carthage will then pull and build the required Frameworks, which you can then manually add into your Xcode project file. This should let you continue to use Pods without use_frameworks

**Comment by headlessme** [comment]
You can find more about the core issue with Pods + use_frameworks + Swift dependencies here: https://github.com/CocoaPods/CocoaPods/issues/3839

**Comment by ramakula** [comment]
Yeah I'm aware of pods request that's been asked for years now :) I'm going to use carthage for cobrowse. Thanks for prompt replies.
