### ISSUE TITLE
Doing yarn after adding this dependency in package.json, there is error in the CobrowseView.js

### ISSUE THREAD

**Issue by KiranCNayak** [cobrowseio/cobrowse-sdk-react-native#7]
This function is missing a closing paranthesis in the else if block. Line 115 in node_modules/cobrowse-sdk-react-native/js/CobrowseView.js

        renderContent() {

            const { error, session } = this.state;

            if (error) {

                return this.renderError();

            } else if ((!session) || ((session.state === 'pending' || session.state === 'authorizing')) {

                return this.renderCode();

            } else {

                return this.renderManageSession();

            }

        }

**Comment by headlessme** [comment]
Thanks for reporting. Fixed in 2.3.1
